language: cpp
dist: bionic

before-script:
  - ./.travis/install-automake.sh
script: ./autogen.sh && ./configure && make && make check && make distcheck

compiler:
- gcc
- clang

addons:
  apt:
    packages:
    - autoconf
    - libboost-system-dev
    - libboost-filesystem-dev
    install:
    - flex

after-success:
 - (bash <(curl -s https://codecov.io/bash) && echo "Sent coverage reports to Codecov") || echo "Codecov did not collect coverage reports"