name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: get dependencies
        run: sudo apt-get install libboost-filesystem-dev flex
      - name: generate configure
        run: ./autogen.sh
      - name: run configure
        run: ./configure
      - name: make
        run: make
      - name: make check
        run: make check
      - name: make distcheck
        run: make distcheck